version: '3.4'

services:
  booki:
    image: ${DOCKER_REGISTRY-}booki
    container_name: booki
    ports:
        - "5001:80"
        - "5000:433"
    build:
      context: .
      dockerfile: Booki/Dockerfile
    volumes:
      - "C:/images:/images" #volume name:path for app images.
  bookidatabase:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: booki_database
    ports:
        - "1433:1433" #Host:Container
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=pass123#Evan
        - MSSQL_PID=Express
    volumes:
      - "C:/Data/Booki:/var/opt/mssql/data" #volume name:path for db data.